### ISSUE TITLE
AT&T style assembly code used in textbook example--confusing

### ISSUE THREAD

**Issue by astrastella** [GrayHatHacking/GHHv6#9]
I was reading the ebook version of the textbook and since it says all the examples will be in NASM syntax, the exception on the example for lea is given in AT&T syntax, which is very confusing. This is especially so because we see the NASM syntax  in the table directly below it, with the order of source and destination reversed. 

<img width="590" alt="Screen Shot" src="https://github.com/GrayHatHacking/GHHv6/assets/30526463/860d83b2-829c-4cc1-b609-9c8fcb362afa">

I also tried to search for an errata of the textbook but could not find any result, therefore posting here.

**Comment by harperaa** [comment]
Thanks for the feedback. We will attempt to clarify it if we do another
version. As the table says, AT&T is given as an example.

Allen
